### ISSUE TITLE
Project no longer runs

### ISSUE THREAD

**Issue by markhorsell** [daily-demos/svelte-call-object#8]
Error: Function called outside component initialization
    at get_current_component (/node_modules/svelte/internal/index.mjs:940:15)
    at Module.setContext (/node_modules/svelte/internal/index.mjs:970:5)
    at eval (/.svelte-kit/generated/root.svelte:17:24)
    at $$render (/node_modules/svelte/internal/index.mjs?v=f0ce49dc:1701:22)
    at Object.render (/node_modules/svelte/internal/index.mjs?v=f0ce49dc:1709:26)
    at render_response (file:///home/mark/Documents/projects/svelte-daily/.svelte-kit/runtime/server/index.js:1202:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async respond_with_error (file:///home/mark/Documents/projects/svelte-daily/.svelte-kit/runtime/server/index.js:2632:10)
    at async respond$1 (file:///home/mark/Documents/projects/svelte-daily/.svelte-kit/runtime/server/index.js:2887:4)
    at async resolve (file:///home/mark/Documents/projects/svelte-daily/.svelte-kit/runtime/server/index.js:3267:11)

**Comment by jessmitch42** [comment]
Thanks for flagging! I've confirmed the error and will post here when the fix is live.

**Comment by markhorsell** [comment]
Thanks for being so quick. The app runs now but i cant connect. I wonder if this is to do with the port? My localhost is being set to 5173 but the readme suggests it should be 3000

**Comment by jessmitch42** [comment]
Ah, yes, use 5173. I'll update the README :) Oversight on my end.

**Comment by markhorsell** [comment]
Failed to load call object bundle https://https/static/call-machine-object-bundle.js: TypeError: Failed to fetch

**Comment by markhorsell** [comment]
https twice there?

**Comment by jessmitch42** [comment]
Can you provide some more information on steps for reproducing this please?
Are you creating a room (pressing the "create room" button on the home screen)? Or are you providing an existing Daily room URL and pressing "Join room"? A screenshot would be helpful if possible so I can see what you're submitting in the form.

Second possibility - is your `VITE_DAILY_DOMAIN` in your environment variables `https://example-domain.daily.co` or just `example-domain` (so the subdomain of any Daily room links you're using). It should be just the `example-domain` part of your Daily links.

Once we sort out the solution, I can add clarification to the README for other devs who might hit this.
(It works for me locally so I would assume this might be a miscommunication in the README.)

**Comment by markhorsell** [comment]
Yes. In the sample.env it says 

# any room URL (e.g. https://YOUR-DOMAIN.daily.co/room-name)

which suggests

VITE_DAILY_DOMAIN="https://YOUR-DOMAIN.daily.co/room-name"

but works if i just use

VITE_DAILY_DOMAIN="YOUR-DOMAIN.daily.co"

so just a change there 

This gets me into the room and i can chat to another instance of myself in a different tab so should be good now :)

Thankyou for the prompt help :)

**Comment by jessmitch42** [comment]
That's great! Thanks for confirming and flagging this. I'll add a little update to make this a little clearer for others too.
